version: '3'

services:
  query-service:
    build: ./wikidata-query-service
    image: wikidata-query-service:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./wikidata:/wikidata/data

  loader:
    build: ./wikidata-loader
    image: wikidata-loader:latest
    environment:
      - WIKI_LANG_PARAM=
      - WIKI_UPDATE_SLEEP_SEC=172800
    restart: "unless-stopped"
    volumes:
      - ./loader-data:/wikidata/data
      - ./loader-logs:/wikidata/logs


